baseurl = "/"
title = "Achmad Fatoni"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Coding Notes"
    description = "------"
    github = "https://github.com/achmadfatoni"
    twitter = "https://twitter.com/achmadfatoniii"
    email = "hi@achmadfatoni.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"